/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product } from './types';

export const initialProducts: Product[] = [
  {
    id: "p1",
    nameHy: "Կայսերական Միկադո",
    nameEn: "Royal Mikado Cake",
    descriptionHy: "Ավանդական հայկական սիրված տորթ՝ թարմ եփված խտացրած կաթով կրեմով և բարակ, նուրբ շերտերով, պատված պրեմիում դասի քերած շոկոլադով։",
    descriptionEn: "A traditional Armenian holiday favourite. Dozens of micro-thin crisp layers bonded with a caramelized dulce de leche cream and topped with premium dark chocolate shavings.",
    price: 11000,
    rating: 4.9,
    reviewsCount: 142,
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=600",
    category: "cakes",
    isCustomizable: false,
    preparationTimeHy: "3 ժամ",
    preparationTimeEn: "3 hours",
    popular: true
  },
  {
    id: "p2",
    nameHy: "Կարմիր Վելվետ Սիմֆոնիա",
    nameEn: "Red Velvet Symphony",
    descriptionHy: "Զարմանահրաշ վառ կարմիր բիսկվիթներ՝ նուրբ շոկոլադային երանգով, պատված բարձրորակ սերուցքային պանրով (Cream Cheese) պատրաստված թավշյա կրեմով։",
    descriptionEn: "Lush cocoa-infused crimson sponge layers balanced perfectly with a premium, velvety cream cheese frosting and edible gold details.",
    price: 14500,
    rating: 4.8,
    reviewsCount: 94,
    image: "https://images.unsplash.com/photo-1586985289688-ca9cf49d3ad3?auto=format&fit=crop&q=80&w=600",
    category: "cakes",
    isCustomizable: true,
    preparationTimeHy: "4 ժամ",
    preparationTimeEn: "4 hours",
    popular: true
  },
  {
    id: "p3",
    nameHy: "Տնական Մեղրով Տորթ (Մեդովիկ)",
    nameEn: "Classic Honey Medovik",
    descriptionHy: "Նուրբ մեղրային շերտեր՝ թթվասերային թեթև կրեմով, որոնք հալվում են բերանում։ Պատրաստվում է բնական և թարմ Արցախյան մեղրով։",
    descriptionEn: "Delicate honey-infused layers sweetened with organic mountain honey, alternated with smooth, light sour-cream whip that dissolves delightfully on the tongue.",
    price: 9500,
    rating: 4.95,
    reviewsCount: 210,
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=600",
    category: "cakes",
    isCustomizable: true,
    preparationTimeHy: "2.5 ժամ",
    preparationTimeEn: "2.5 hours",
    popular: true
  },
  {
    id: "p4",
    nameHy: "Ավանդական Կլոր Գաթա",
    nameEn: "Traditional Armenian Gata",
    descriptionHy: "Ըստ հին հայկական բաղադրատոմսի պատրաստված կարագով և քաղցր խորիզով լցված անուշահոտ գաթա՝ նախշազարդված վերնամասով։",
    descriptionEn: "Authored by ancient recipes, this iconic Armenian puff pastry is stuffed with sweet buttery 'Khoriz' core, baked to a golden crust with traditional patterns.",
    price: 3200,
    rating: 5.0,
    reviewsCount: 320,
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=600",
    category: "armenian_sweets",
    isCustomizable: false,
    preparationTimeHy: "2 ժամ",
    preparationTimeEn: "2 hours",
    popular: true
  },
  {
    id: "p5",
    nameHy: "Ճոխ Մեղրով Փախլավա (Արևելյան)",
    nameEn: "Gourmet Honey Pakhlava",
    descriptionHy: "Բազմաշերտ խրթխրթան թերթիկներ՝ լցված ընտրովի մանրացված ընկույզով, հիլով և համեմված բնական մեղրի օշարակով։",
    descriptionEn: "Crispy layers of flaky phyllo dough loaded with choice walnuts, cardamon spices, and excessively saturated in pure, warm organic honey syrup.",
    price: 6500,
    rating: 4.88,
    reviewsCount: 88,
    image: "https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&q=80&w=600",
    category: "armenian_sweets",
    isCustomizable: false,
    preparationTimeHy: "4 ժամ",
    preparationTimeEn: "4 hours"
  },
  {
    id: "p6",
    nameHy: "Շոկոլադե Ֆաջ Գլազուրով",
    nameEn: "Glossy Chocolate Fudge",
    descriptionHy: "Հարուստ շոկոլադե բիսկվիթներ՝ պատված խիտ բելգիական շոկոլադե գանաշով և զարդարված թարմ հատապտուղներով։",
    descriptionEn: "Indulgent Belgian dark chocolate sponge cake, layered with rich fudge ganache and decorated beautifully with handpicked fresh wild forest berries.",
    price: 13000,
    rating: 4.75,
    reviewsCount: 76,
    image: "https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&q=80&w=600",
    category: "cakes",
    isCustomizable: true,
    preparationTimeHy: "3 ժամ",
    preparationTimeEn: "3 hours"
  },
  {
    id: "p7",
    nameHy: "Պիստակով և Մալինայով Տորթ",
    nameEn: "Pistachio & Raspberry Dream",
    descriptionHy: "Պիստակային բնական բիսկվիթ՝ թարմ ազնվամորու կուլիով և թեթև կրեմով։ Իդեալական է թեթև համերի սիրահարների համար։",
    descriptionEn: "Vibrant ground-pistachio sponge sheets layered with sweet forest raspberry reduction and premium whipped white chocolate cream.",
    price: 16000,
    rating: 4.92,
    reviewsCount: 112,
    image: "https://images.unsplash.com/photo-1535141192574-5d4897c13636?auto=format&fit=crop&q=80&w=600",
    category: "cakes",
    isCustomizable: true,
    preparationTimeHy: "5 ժամ",
    preparationTimeEn: "5 hours"
  },
  {
    id: "p8",
    nameHy: "Ֆրանսիական Մակարոնների Հավաքածու",
    nameEn: "Assorted French Macarons",
    descriptionHy: "12 հատ նուրբ նուշի ալյուրով պատրաստված մակարոններ՝ պիստակի, մալինայի, լիմոնի և աղի կարամելի նուրբ միջուկներով։",
    descriptionEn: "A gift set of 12 airy almond meringue shells in natural pastel tones, presenting rich Pistachio, Raspberry, Lemon, and Salted Caramel ganache centers.",
    price: 7200,
    rating: 4.81,
    reviewsCount: 150,
    image: "https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&q=80&w=600",
    category: "pastries",
    isCustomizable: false,
    preparationTimeHy: "1.5 ժամ",
    preparationTimeEn: "1.5 hours"
  },
  {
    id: "p9",
    nameHy: "Հատապտղային Կապույտ Քափքեյքեր",
    nameEn: "Bliss Blueberry Cupcakes",
    descriptionHy: "6 հատ թարմ թխված վանիլային քափքեյքեր՝ լցված հապալասի ջեմով և զարդարված երկնագույն նուրբ սերուցքային կրեմով։",
    descriptionEn: "6 fluffy gold-baked cupcakes containing dynamic high-mountain blueberry cores, capped with heavenly blueberry whip and candy sprinkles.",
    price: 4900,
    rating: 4.7,
    reviewsCount: 64,
    image: "https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&q=80&w=600",
    category: "cupcakes",
    isCustomizable: false,
    preparationTimeHy: "1 ժամ",
    preparationTimeEn: "1 hour"
  },
  {
    id: "p10",
    nameHy: "Կարամելային Էկլերների Տուփ",
    nameEn: "Salted Caramel Eclairs Trio",
    descriptionHy: "Շու խմորով պատրաստված 3 նուրբ էկլերներ՝ լցված թեթև եփովի կրեմով և պատված անուշահոտ տնական աղի կարամելով։",
    descriptionEn: "Trio of perfectly puffed choux pastries loaded with a core of Madagascan vanilla custard and drizzled with warm sea-salt caramelized sugar glaze.",
    price: 3600,
    rating: 4.89,
    reviewsCount: 104,
    image: "https://images.unsplash.com/photo-1603532648955-039310d9ed75?auto=format&fit=crop&q=80&w=600",
    category: "pastries",
    isCustomizable: false,
    preparationTimeHy: "1.5 ժամ",
    preparationTimeEn: "1.5 hours"
  }
];
